# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jennifer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='description',
            new_name='abstract',
        ),
        migrations.AlterField(
            model_name='publication',
            name='isbn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pubDate',
            field=models.DateField(),
        ),
    ]
