# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 11:25
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jennifer', '0003_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5)),
                ('graduationYear', models.CharField(max_length=4)),
                ('fullTitle', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
