# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jennifer', '0004_auto_20170429_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='fullTitle',
            new_name='name',
        ),
    ]
