# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jennifer', '0006_award_position_teaching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='yearEnd',
            field=models.SmallIntegerField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='award',
            name='yearStart',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduationYear',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='yearEnd',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='yearStart',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='yearEnd',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='yearStart',
            field=models.SmallIntegerField(),
        ),
    ]
