# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jennifer', '0007_auto_20170429_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='yearEnd',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
